defaults:
  - iql: iql
  - nn: nn
  - ccnn_img: ccnn_img
  - ccnn_seq: ccnn_seq
  - _self_

hydra:
  run:
    dir: outputs/${now:%Y-%m-%d/%H-%M-%S}

distributed:
  device_ids: [0, 1, 2, 3, 4, 5, 6, 7]
  multiprocessing_distributed: True
  world_size: 8
  port: 12392

experiment:
  seed: 5
  device: 3
  gamma: 0.99
  env_type: "gym"
  num_envs: 8 # envpool num_envs

  # async_batch_size: 32
  total_timesteps: 1000000 # Total time steps to run environment
  save_ckpt: True
  num_checkpoints: 20
  print_interval: 100 # print iverval of episodic return
  stop_after_epochs: 500 # early stopping epochs
  capture_video: False
  cuda: True
  torch_deterministic: True
  load_ckpt: False
  resume: False
  resume_update_idx: 0
  resume_dir: None # output/2023-06-16/23-51-58/
  env_ids: [
    #  'halfcheetah-medium-v2',
#  'halfcheetah-medium-replay-v2',
 'halfcheetah-medium-expert-v2',
#  'maze2d-umaze-v1',
#  'maze2d-medium-v1',
#  'maze2d-large-v1',
  # 'hopper-medium-v2',
#  'hopper-medium-replay-v2',
 'hopper-medium-expert-v2',
#  'walker2d-medium-v2',
#  'walker2d-medium-replay-v2',
 'walker2d-medium-expert-v2',
  # 'hammer-human-v1',
 'hammer-expert-v1',
#  'hammer-cloned-v1',
#  'pen-human-v1',
#  'pen-cloned-v1',
 'pen-expert-v1',
#  'relocate-human-v1',
#  'relocate-cloned-v1',
 'relocate-expert-v1',
#  'door-human-v1',
#  'door-cloned-v1',
 'door-expert-v1',
  'antmaze-umaze-v2', #
#  'antmaze-umaze-diverse-v2', #
#  'antmaze-medium-play-v2', #
#  'antmaze-medium-diverse-v2', #
#  'antmaze-large-play-v2', #
#  'antmaze-large-diverse-v2', #
  ]
finetuning_env_ids: [

#     'maze2d-open-v0',
#  'maze2d-eval-umaze-v1',
#  'maze2d-eval-medium-v1',
#  'maze2d-eval-large-v1',
#  'maze2d-open-dense-v0',
#  'maze2d-umaze-dense-v1',
#  'maze2d-medium-dense-v1',
#  'maze2d-large-dense-v1',
#  'maze2d-eval-umaze-dense-v1',
#  'maze2d-eval-medium-dense-v1',
#  'maze2d-eval-large-dense-v1',
#  'minigrid-fourrooms-v0',
#  'minigrid-fourrooms-random-v0',
#  'pen-human-v0',
#  'pen-cloned-v0',
#  'pen-expert-v0',
#  'hammer-human-v0',
#  'hammer-cloned-v0',
#  'hammer-expert-v0',
#  'relocate-human-v0',
#  'relocate-cloned-v0',
#  'relocate-expert-v0',
#  'door-human-v0',
#  'door-cloned-v0',
#  'door-expert-v0',
#  'halfcheetah-random-v0',
#  'halfcheetah-medium-v0',
#  'halfcheetah-expert-v0',
#  'halfcheetah-medium-replay-v0',
#  'halfcheetah-medium-expert-v0',
#  'walker2d-random-v0',
#  'walker2d-medium-v0',
#  'walker2d-expert-v0',
#  'walker2d-medium-replay-v0',
#  'walker2d-medium-expert-v0',
#  'hopper-random-v0',
#  'hopper-medium-v0',
#  'hopper-expert-v0',
#  'hopper-medium-replay-v0',
#  'hopper-medium-expert-v0',
#  'ant-random-v0',
#  'ant-medium-v0',
#  'ant-expert-v0',
#  'ant-medium-replay-v0',
#  'ant-medium-expert-v0',
#  'ant-random-expert-v0',
#  'antmaze-umaze-v0',
#  'antmaze-umaze-diverse-v0',
#  'antmaze-medium-play-v0',
#  'antmaze-medium-diverse-v0',
#  'antmaze-large-play-v0',
#  'antmaze-large-diverse-v0',

#  'flow-ring-random-v0',
#  'flow-ring-controller-v0',
#  'flow-merge-random-v0',
#  'flow-merge-controller-v0',
#  'kitchen-complete-v0',
#  'kitchen-partial-v0',
#  'kitchen-mixed-v0',
#  'carla-lane-v0',
#  'carla-town-v0',
#  'carla-town-full-v0',
#  'bullet-halfcheetah-random-v0',
#  'bullet-halfcheetah-medium-v0',
#  'bullet-halfcheetah-expert-v0',
#  'bullet-halfcheetah-medium-expert-v0',
#  'bullet-halfcheetah-medium-replay-v0',
#  'bullet-hopper-random-v0',
#  'bullet-hopper-medium-v0',
#  'bullet-hopper-expert-v0',
#  'bullet-hopper-medium-expert-v0',
#  'bullet-hopper-medium-replay-v0',
#  'bullet-ant-random-v0',
#  'bullet-ant-medium-v0',
#  'bullet-ant-expert-v0',
#  'bullet-ant-medium-expert-v0',
#  'bullet-ant-medium-replay-v0',
#  'bullet-walker2d-random-v0',
#  'bullet-walker2d-medium-v0',
#  'bullet-walker2d-expert-v0',
#  'bullet-walker2d-medium-expert-v0',
#  'bullet-walker2d-medium-replay-v0',
#  'bullet-maze2d-open-v0',
#  'bullet-maze2d-umaze-v0',
#  'bullet-maze2d-medium-v0',
#  'bullet-maze2d-large-v0',
#  'halfcheetah-random-v1',
#  'halfcheetah-random-v2',
#  'halfcheetah-medium-v1',
#  'halfcheetah-expert-v1',
#  'halfcheetah-expert-v2',
#  'halfcheetah-medium-replay-v1',
#  'halfcheetah-full-replay-v1',
#  'halfcheetah-full-replay-v2',
#  'halfcheetah-medium-expert-v1',
#  'hopper-random-v1',
#  'hopper-random-v2',
#  'hopper-medium-v1',
#  'hopper-expert-v1',
#  'hopper-expert-v2',
#  'hopper-medium-replay-v1',

#  'hopper-full-replay-v1',
#  'hopper-full-replay-v2',
#  'hopper-medium-expert-v1',
#  'walker2d-random-v1',
#  'walker2d-random-v2',
#  'walker2d-medium-v1',
#  'walker2d-expert-v1',
#  'walker2d-expert-v2',
#  'walker2d-medium-replay-v1',
#  'walker2d-full-replay-v1',
#  'walker2d-full-replay-v2',
#  'walker2d-medium-expert-v1',
#  'ant-random-v1',
#  'ant-random-v2',
#  'ant-medium-v1',
#  'ant-medium-v2',
#  'ant-expert-v1',
#  'ant-expert-v2',
#  'ant-medium-replay-v1',
#  'ant-medium-replay-v2',
#  'ant-full-replay-v1',
#  'ant-full-replay-v2',
#  'ant-medium-expert-v1',
#  'ant-medium-expert-v2',

]

evaluation:
  eval_seed: 42
  eval_freq: 5000
  every: 5
  n_episodes: 10 # the number of episodes for evaluation
  # num_test_envs: 8 # gymnasium Syncvector num_envs

wandb:
  mode: online
  project: HMRL
  entity: null
  name: null
  group: 'DDIQL'
  tags: null
  notes: null

paths:
  dir: outputs/${now:%Y-%m-%d/%H-%M-%S}
  log: outputs/${now:%Y-%m-%d/%H-%M-%S}/runs
  video: outputs/${now:%Y-%m-%d/%H-%M-%S}/videos 
  checkpoints: outputs/${now:%Y-%m-%d/%H-%M-%S}/checkpoints 
  src: outputs/${now:%Y-%m-%d/%H-%M-%S}/src 
  scripts: outputs/${now:%Y-%m-%d/%H-%M-%S}/scripts 